apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: t3kxro3ys-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/rhtap-qe:3c3483614a094f0f87ceee92285d6080fec3e639@sha256:f72bf241e0d31078c4b8dd82d7afdb69fba40dbc747bbb580fcf80b7e27b20cb
        name: container-image  
